### ISSUE TITLE
1 to do and 2 small problems

### ISSUE THREAD

**Issue by CinziaGrifoni** [acdh-oeaw/matc#1]
@tklampfl 
Lieber Thomas, beim Transkribieren sind weitere (schon bekannte) althochdeutsche Glossen aufgepoppt. Kannst Du sie bitte im Fenster "Old High German Glosses" inkludieren?

Problemchen:
 - ich schaffe es immer noch nicht, vom Laptop die Transformation erfolgreich durchzuführen. Am PC gelingt es nur, wenn ich sie im Commit inkludiere. Beim nächsten Treffen können wir bitte wieder anschauen, was am Laptop nicht passt?
 - ich habe die xml:id #gl-1 zu #Otfrid geändert, aber ich habe offensichtlich etwas falsch gemacht: in der Edition auf der Webseite, bei der Analyse-Hand ist die Zeile leer, wo Otfrid stehen sollte.
 
Danke für Deine Hilfe! Bis bald, Cinzia

**Comment by tklampfl** [comment]
Liebe Cinzia,
folgendes konnte ich erledigen:
- die Seite mit den althochdeutschen Glossen ist aktualisiert.
- es gibt nun eine Seite nur mit den Glossen: [siehe hier](https://priscian-glosses.acdh-dev.oeaw.ac.at/edition-simplified.html)
- Der Schreiber _Otfrid_ ist nun in der Transformation berücksichtigt.

Ich möchte dich bitten, einen Blick darauf zu werfen, und mir Fehler mitzuteilen.
Was noch fehlt:
- Einbindung der vereinfachten Edition in die Navigation.

Aufgefallen ist mir:
- Die Texte in griechischer Schrift werden nicht schön dargestellt. Hier könnte ich einen Web-Schriftsatz einbinden. Allerdings wäre die Voraussetzung, dass du die griechischen Texte eigens auszeichnest, z.B. mit `foreign xml:lang=grc`.
- Es sind in der Transkription Informationen enthalten, die sich in keiner Ausgabe finden: Die Handschriftenbeschreibung, die Bibliographie und die Editionsprinzipien. Das sollten wir eventuell irgendwo unterbringen, z.B. in der Datei `edition.html`.

Ich habe am Donnerstag um 9:00 Uhr eine Besprechung zum Expositiones in Psalmos Projekt, und könnte im Anschluß bei dir vorbeikommen. Allerdings kann ich keinen genauen Zeitpunkt nennen.
Ich bin für alle Hinweise zu Fehlern und Verbesserungen dankbar.
Liebe Grüße, Thomas

**Comment by CinziaGrifoni** [comment]
[Verbesserungen 19.2.24.docx](https://github.com/acdh-oeaw/matc/files/14329990/Verbesserungen.19.2.24.docx)
Lieber Thomas,
Die Edition-simplified passt sehr gut, finde ich.
Ich schicke Dir im Anhang was mir aufgefallen an Verbesserungsvorschlägen.

Danke für die Aktualisierung des Fensters "Old High German Glosses". Hier ist mir aufgefallen, dass es beim Neufund (d.h. bei der zweiten Glosse in der Liste) zweimal "first glossator" statt "Otfrid" aufscheint. Könntest Du bitte das auch hier ändern?

Am Donnerstag kann ich im Büro bis 14:30h bleiben. Wenn es sich mit deiner vorigen Besprechung ausgeht, können wir uns gerne treffen. Ich bin da. Solltest Du es brauchen, das ist meine Handynummer: 0699-17097533.
Wir könnten am Donnerstag die Texte in griechischer Schrift besprechen, die fehlenden Informationen in der Datei edtion.html zusammen ergänzen, und das Problem bei der Transformation an meinem Laptop anschauen.
Danke Dir, liebe Grüße
Cinzia

**Comment by CinziaGrifoni** [comment]
Erledigt.
