### ISSUE TITLE
Kleinigkeiten und neue Wünsche

### ISSUE THREAD

**Issue by CinziaGrifoni** [acdh-oeaw/matc#3]
Lieber Thomas,
hier vier Kleinigkeiten, die zu ändern wären:
-Ich habe gestern eine neue OHG-Glosse kodiert, die Nr. 7, kein Neufund. Könntest Du sie bitte ins Fenster „Old High German Glosses“ aufnehmen?
- In der edition.html, unter „Description of the manuscript“ könntest Du bitte die ersten drei Punkte nur in eine Zeile zusammenbringen (•  Wolfenbüttel, Herzog August Bibliothek, Weißenburger Handschriften). Außerdem, kannst Du bitte vor die Zeile „Heinemann-Nr. 4134“ folgende Zeile hinzufügen: •Hans Butzmann, Die Weißenburger Handschriften, p. 187.
- wenn ich so etwas kodiere: <lem wit="#EDITION"><foreign xml:lang="grc">Ἀλκμάν</foreign></lem> bleibt in der Transformation die Zeile leer. Das habe ich bei II 17,11; 17,12; 24, 17 (mehrere Einträge) bemerkt. 
- Bei gloss-17-4-2-: In der Transformation sollten die Worte, die ich zwischen "del" kodiert habe, durchstrichen aufscheinen, jetzt werden sie normal dargestellt.

                  
****
Ich hätte drei weitere Vorschläge, um die Lesbarkeit der Transformation zu erhöhen, aber sag mir bitte zuerst, ob sie machbar sind.:
- im Fenster „Old High German Glosses“ könnte man die Einträge durchnummerieren und ein bisschen mehr Abstand zwischen ihnen lassen.
- in allen drei Versionen der Transformation (Edition, interactive und simplified) könnte man den Text der Glossen und Emendations farbig darstellen (zum Beispiel  Hellblau). Bei Glossen müsste das nur den Text der Glosse und die Glyphen für abbreviations betreffen (scilicet, est, id est, vel, irish-et, quae), nicht die reference signs oder die annotation signs, die evtl. eine Glosse einleiten. Ähnlich bei Emendations (nur der Text könnte farbig aufscheinen).
- könnte man in allen drei Version die quotes, also die Zeilen aus Priscian, mit einem ein bisschen größeren Font darstellen? damit die Einteliung des Textes übersichtlicher ist - aber ich bin selber nicht sicher, ob das eine gute Idee ist. Was denkst Du?

Danke Dir vielmals!
Cinzia

**Comment by tklampfl** [comment]
Die althochdeutschen Glossen Nummer sieben und acht finden sich auf der Seite "Old High German Glosses". Eine Zählung wurde eingeführt, und der Abstand zwischen den Glossen erhöht.
![grafik](https://github.com/acdh-oeaw/matc/assets/56353369/270a4108-2d05-45c6-877b-330792ce5abc)

**Comment by tklampfl** [comment]
Handschriftenbeschreibung geändert:
![grafik](https://github.com/acdh-oeaw/matc/assets/56353369/e43424ca-7534-4ca2-954e-1ca54be07057)

**Comment by tklampfl** [comment]
Glosse ```gloss-17-14-2```: ```del``` in Transformation berücksichtigt. ```#``` im folgenden ```hand``` Attribut hat gefehlt.
![grafik](https://github.com/acdh-oeaw/matc/assets/56353369/f2a9aed4-d228-42a0-8fe1-fdcea203c0dc)
