### ISSUE TITLE
letters filled with red ink

### ISSUE THREAD

**Issue by CinziaGrifoni** [acdh-oeaw/matc#4]
Lieber Thomas,
ich habe vorhin meine heutige Kodierung mit der ohg-gloss Nummer 8 gepusht. 
Bei der Kontrolle habe ich ein Problem bei der Transformation der app-rubrication im Fall von "hi rend=letter filled with red ink" entdeckt. Ein Beispiel ist die xml:id= rubr-25-13-2, bei der zwei Buchstaben betroffen sind. 
Wäre es bitte möglich, dass auch bei dieser rend die Buchstaben in der Transformation rot erscheinen?
Danke Dir, einen schönen Nachmittag
Cinzia

**Comment by tklampfl** [comment]
Ich habe zwei Fälle entdeckt: ```letter filled with red ink``` und ```capital letter filled with red ink```. Beide Fälle wurden in der Transformation berücksichtigt, und sind nun in der Edition rot.
In der Rubrik ```rubr-25-13-2``` finden sich zwei ```hi``` Elemente im ```rdg```. Der Wert des ```rend``` Attributs wird als Intervention in der Darstellung ausgewiesen. D.h. es finden sich zwei Änderungen; diese habe ich mit Bindestrich getrennt in die eckige Klammer geschrieben. Alternativ müßte jeder Eingriff als eigene Rubrik kodiert werden.
Rubrik ```rubr-3-16-1```:
![grafik](https://github.com/acdh-oeaw/matc/assets/56353369/a89a5079-cf2d-4737-a73b-f26c521de638)
Rubrik ```rubr-25-13-2``` (mit zwei Eingriffen):
![grafik](https://github.com/acdh-oeaw/matc/assets/56353369/bf324e24-68c2-47bb-b9c7-b9d29d3a6110)

**Comment by CinziaGrifoni** [comment]
Danke, vielmals, alles perfekt!
