### ISSUE TITLE
Text der Glosse in Farbe, Auswertung, lemma mit größerem Font

### ISSUE THREAD

**Issue by CinziaGrifoni** [acdh-oeaw/matc#6]
Lieber Thomas,

kannst du bitte in allen drei Versionen der Transformation (Edition, interactive und simplified)  den Text der Glossen farbig darstellen? Damit meine ich den Text der Glosse und die Glyphen für abbreviations (scilicet, est, id est, vel, irish-et, quae), nicht die reference signs oder die annotation signs, die evtl. eine Glosse einleiten.

Bez. Auswertung, könntest Du sie bitte so konfigurieren?: 
1) betreffend nur die app type=gloss
2) zuerst bräuchte ich eine Auswertung von hand, so dass ich erfahre, wie viele Glossen in Summe jede Hand geschrieben hat
3) dann bräuchte ich pro jede Hand eine Auswertung von place, so dass ich erfahre wie viele Interlinearglossen und wie viele Marginalglossen jede Hand geschrieben hat
4) als letztes würde ich gerne sehen, wie viele Glossen pro jede (ana) die jeweilige Hand im jeweiligen Place geschrieben hat.
Durch die Auswertung möchte ich zum Beispiel folgende Fragen beantwortem: Wie viele Glossen hat Otfrid im ersten Buch geschrieben? Wie viele von Otfrid's Glossen sind interlinear, wie viele Randglossen? Wie viele von den Interlinearglossen sind ana=Synonyms? Wie viele von den Marginalglossen sind ana="lexical Glossen"? Dasselbe für die anderen Hände.

Kannst Du bitte Priscians Zeilen in allen Transformationen (Edition, interactive und simplified) mit einem größeren Font darstellen?

Ich danke Dir sehr! Liebe Grüße
Cinzia

**Comment by tklampfl** [comment]
In der Datei ```edition-simplified.html``` ist der Text der Glossen nun farblich hinterlegt. Für Glyphen gilt dies nur, wenn sie zur Klasse der _abbreviations_ zählen.
![grafik](https://github.com/acdh-oeaw/matc/assets/56353369/14330c03-6e95-462d-8894-bc7a4ec30e72)
In derselben Datei findet sich ein Entwurf einer statistischen Auswertung.

Der Text der Edition ist um zwei Punkte größer gesetzt.

**Comment by tklampfl** [comment]
Auch in der Datei ```edition.html``` ist der Text der Glossen nun hervorgehoben.
