### ISSUE TITLE
Adjustments

### ISSUE THREAD

**Issue by CinziaGrifoni** [acdh-oeaw/matc#7]
Lieber Thomas,
ich bin endlich mit der Transkription vom ersten Buch fertig geworden, Bei der Nachprüfung sind mir wenige Sachen aufgefallen, die geändert werden sollen. Ich liste sie hier unten auf und möchte Dich bitten, sie anzuschauen.
1) Kannst Du bitte "Navigation buttons" für Praefatio, Liber Primus, Liber Secundus bei den Ausgaben "Edition", "Simplified" und "Interactive Edition" erstellen? Und auch "Go to the top" buttons?
2) Die Fenster OHG-Glosses, Simplified Edition, Interactive Edition sollen bitte aktualisiert werden.
3) Bei den Statistics: Wäre es bitte möglich, sie zu aktualisieren und diese auch in Praefatio, Liber Primus, Liber Secundus zu unterscheiden? Die Statistics sollen die schon vorhandene Struktur beibehalten aber die Daten zwischen Praefatio, Liber Primus und Liber Secundus ensprechend aufteilen, wenn möglich. So kann ich wissen, wie viele Glossen im Liber Primus vorkommen, wie viele im Secundus usw.
4) Bei der Ausgabe von "notes" in "Edition" bitte auch die "targets" inkludieren, damit es klar ist, auf was sich die "note" bezieht, vor allem wenn sich die "note" auf mehrere Targets bezieht, Wenn möglich, "notes" sollten auch bei der "Simplified" und bei der "Interactive Edition" aufscheinen.
5) Bei der "rubrication 42-10-1", 42-14-1, 42-14-2 usw. scheint <hand="#Otfrid"> nicht auf.
6) in der Ausgabe "Edition", am Anfang, da wo die Abbidungen der Zeichen vorkommen: Könntest Du bitte die Abbildung von REFERENCE SIGN DOTTED GAMMA verkleinern?

Herzlichen Dank für Deine Zeit, Arbeit und Unterstützung!
Liebe Grüße
Cinzia

**Comment by tklampfl** [comment]
Added old high german glosses number 9 to 16:
- ```gloss-27-1-1```
- ```gloss-30-22-4```
- ```gloss-30-22-5```
- ```gloss-33-21-1```
- ```gloss-36-16-2```
- ```gloss-36-22-1```
- ```gloss-38-5-1```
- ```gloss-42-9-4```

to the file ```old-high-german-glosses.html```

**Comment by tklampfl** [comment]
Corrected size of image REFERENCE SIGN DOTTED GAMMA:
![grafik](https://github.com/user-attachments/assets/b2aeeefe-8561-4a2e-9e0b-86f97a177694)
Please note that the ```graphic``` element can have an attribute ```width``` and ```height``` which control the size of the picture.

**Comment by tklampfl** [comment]
Made web link work in note on gloss ```gloss-42-9-4```.
Please note that it is necessary to use the ```target``` attribute on ```ref``` for the web address.

**Comment by tklampfl** [comment]
Made scribe ```Otfrid``` available for rubrications.
![grafik](https://github.com/user-attachments/assets/c64ff75d-1252-4994-9692-a600012571c3)

**Comment by tklampfl** [comment]
In ```edition.html``` is a navigation available.
![grafik](https://github.com/user-attachments/assets/d2674934-0c10-4e4f-89a0-386d09d58d3a)

**Comment by tklampfl** [comment]
Added rule for reference(s) on note in transformation for ```edition.html```.
![grafik](https://github.com/user-attachments/assets/9139fad6-1f9e-4641-abfc-55ff87ce41ca)

**Comment by tklampfl** [comment]
Added rules for ```hi``` elements.
![grafik](https://github.com/user-attachments/assets/91842ab0-606f-49d3-8516-4eae303e25b6)

**Comment by tklampfl** [comment]
Transformed page with statistics anew and added rules for calculating the interventions per book.
![grafik](https://github.com/user-attachments/assets/34af6534-ad29-4ef6-8d43-acfb7573bb84)

**Comment by tklampfl** [comment]
Simplified and interactive edition now with table of contents and go to top button.

**Comment by CinziaGrifoni** [comment]
Thank you very much, dear Thomas!
